name: EKS Pipeline

on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # ---------- AWS AUTH ----------
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    # ---------- LOGIN TO ECR PUBLIC ----------
    - name: Login to Amazon ECR Public
      run: |
        aws ecr-public get-login-password --region us-east-1 \
        | docker login --username AWS --password-stdin public.ecr.aws

    # ---------- BUILD & PUSH BACKEND IMAGE ----------
    - name: Build & Push Backend Image
      run: |
        docker build -t three-tier-backend:latest Application-Code/backend
        docker tag three-tier-backend:latest \
        public.ecr.aws/u1p9i3k9/three-tier-backend:latest
        docker push public.ecr.aws/u1p9i3k9/three-tier-backend:latest

    # ---------- BUILD & PUSH FRONTEND IMAGE ----------
    - name: Build & Push Frontend Image
      run: |
        docker build -t three-tier-frontend:latest Application-Code/frontend
        docker tag three-tier-frontend:latest \
        public.ecr.aws/u1p9i3k9/three-tier-frontend:latest
        docker push public.ecr.aws/u1p9i3k9/three-tier-frontend:latest

    # ---------- KUBECONFIG ----------
    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig \
          --region $AWS_REGION \
          --name $EKS_CLUSTER_NAME

    # ---------- NAMESPACE ----------
    - name: Ensure namespace exists
      run: |
        kubectl create namespace $NAMESPACE \
          --dry-run=client -o yaml | kubectl apply -f -

    # ---------- MONGODB SECRET ----------
    - name: Apply MongoDB Secret
      run: |
        kubectl apply -n $NAMESPACE -f Kubernetes-Manifests-file/Database/mongo-secret.yaml

    # ---------- DATABASE ----------
    - name: Deploy MongoDB
      run: |
        kubectl apply -n $NAMESPACE -f Kubernetes-Manifests-file/Database/
        kubectl rollout status deployment/mongodb -n $NAMESPACE --timeout=180s

    # ---------- BACKEND ----------
    - name: Deploy Backend
      run: |
        kubectl apply -n $NAMESPACE -f Kubernetes-Manifests-file/Backend/
        kubectl rollout status deployment/api -n $NAMESPACE --timeout=180s

    # ---------- FRONTEND ----------
    - name: Deploy Frontend
      run: |
        kubectl apply -n $NAMESPACE -f Kubernetes-Manifests-file/Frontend/
        kubectl rollout status deployment/frontend -n $NAMESPACE --timeout=180s

    # ---------- INGRESS (ADDED) ----------
    - name: Deploy Ingress
      run: |
        kubectl apply -n $NAMESPACE -f Kubernetes-Manifests-file/ingress.yaml
        kubectl get ingress -n $NAMESPACE

    # ---------- VERIFY ----------
    - name: Verify
      run: |
        kubectl get pods -n $NAMESPACE
        kubectl get svc -n $NAMESPACE
        kubectl get ingress -n $NAMESPACE
